Repository albert-cloudcamp/ejercicios-git-github-cloud-camp, pull requests merged in 2022-09, with the labels that each got.

#6 Agregamos camilo-arango.sh al proyecto
  scripts/camilo-arango.sh
Labels: enhancement

#18 ✨ david-garcia: Add example file
  scripts/david-garcia.sh
Labels: bug, documentation, dev-deploy

#10 Agregamos edison.jaramillo.sh al proyecto
  scripts/edison-jaramillo.sh
Labels: Despliegue-edison.jaramillo

#14 Agregamos luis-lunar.sh al proyecto
  scripts/luis-lunar.sh
Labels: added-file

#9 Agregamos david-lopez.sh al proyecto
  scripts/david-lopez.sh
Labels: bad error 504

#5 Agregamos juan-yepez.sh al nuevo proyecto
  scripts/juan-yepez.sh
Labels: new-juan-yepez

#1 Add file alexander-rodriguez.sh
  scripts/alexander-rodriguez.sh
Labels: documentation

#7 Agregamos carolina-poveda.sh al proyecto
  scripts/carolina-poveda.sh
Labels: dev-deploy

#2 add new sh file
  scripts/victor-suarez.sh
Labels: dev-deploy

#15 Archivo nuevo agregado diego-chavarria
  scripts/diego-chavarria.sh
Labels: documentation

#13 Agregamos sergio-moreno.sh al proyecto
  scripts/sergio-moreno.sh
Labels: bug

#11 Added david-upegui.sh to project
  scripts/david-upegui.sh
Labels: added-file

#12 Agregamos juan-puentes.sh al proyecto
  scripts/juan-puentes.sh
Labels: good first issue, go_live_in_prod

#8 Agregamos carlos-bedoya.sh al proyecto
  scripts/carlos-bedoya.sh
Labels: question

#4 Agregamos albert-ramirez.sh al proyecto.
  scripts/albert-ramirez.sh
Labels: bug, dev-deploy

#19 add new file steven-rodriguez
  scripts/steven-rodriguez.sh.sh
Labels: dev_steven

#24 Estoy Agregando Ernesto-Zerda.sh al proyecto
  scripts/Ernesto-Zerda.sh
Labels: added-file
